### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by ractodev** [DD2480-Group-4/lab2#5]
Notify users regarding commit status of a certain build to ensure working code on a branch before PR. More information regarding the API can be found [here](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28).

**TODO**:
- [x] Interact with GitHub API to update an arbitrary commit status
- [x] Update commit status on received `push` payload (commit-specific)
- [x] Incorporate [target_url](https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28#create-a-commit-status) parameter in HTTP request to link build info (once unique URL generation is working for builds, see #9)
- [x] Create unit tests
